<?php
// Variables
return [
    'creatorName' => 'Akaun Simple',
    'creatorUrl' => 'https://akaunsimple.my',
    'templateName' => 'Classroom',
    'templateSuffix' => 'Akaun Simple',
    'templateVersion' => '1.0.0',
    'templateFree' => false,
    'templateDescription' => 'Classroom management system by Akaun Simple',
    'templateKeyword' => 'classroom, learning management, akaun simple',
    'licenseUrl' => '#',
    'livePreview' => '#',
    'productPage' => '#',
    'support' => 'mailto:akaunsimple.my@gmail.com',
    'moreThemes' => '#',
    'ogTitle' => 'Classroom - Akaun Simple',
    'ogImage' => '',
    'ogType' => 'website',
    'documentation' => '#',
    'generator' => '',
    'changelog' => '#',
    'repository' => '#',
    'gitRepo' => '',
    'gitRepoAccess' => '#',
    'githubFreeUrl' => '#',
    'facebookUrl' => '#',
    'twitterUrl' => '#',
    'githubUrl' => '#',
    'dribbbleUrl' => '#',
    'instagramUrl' => '#',
];
